# name of your github action
name: Build Electron
# this will help you specify where to run 
on:
  push:
    branches:
      - production
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: production
    - uses: actions/setup-node@v2
      with:
        node-version: 14.16
    - name: CI & Build
      run: npm ci && npm run build
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: production
    - uses: actions/setup-node@v2
      with:
        node-version: 14.16
    - name: CI & Build
      run: npm ci && npm run build
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: production
    - uses: actions/setup-node@v2
      with:
        node-version: 14.16
    - name: CI & Build
      run: npm ci && npm run build
